### ISSUE TITLE
What is the license on this data?

### ISSUE THREAD

**Issue by donavon** [hitch17/sample-data#2]
Can I freely use this JSON data in a sample application? Can you please provide a license for the data?  For example, MIT?

Thx

**Comment by hitch17** [comment]
That seems reasonable.  I don't totally remember the source, but all of the
data can be found on wikipedia [
https://en.wikipedia.org/wiki/List_of_Presidents_of_the_United_States].  If
you want to create a pull request to add the wikipedia attribution I'll
merge it in.

Also, just a FYI, the data isn't totally up to date.  George H.W. Bush
(#42) should have a death_year of 2018 and the .js file is actually missing
Trump.  Feel free to add that to the PR too if you'd like.

**Comment by donavon** [comment]
see #3 (license only).

i'll leave the data for a separate PR, as it should be
